title = "The Chain"
baseURL = "https://the-chain.github.io/The-Chain-Site"
tags = ["portfolio", "web design", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
publishDir  = "docs"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Blockchain & AI Solutions"
    author = ""
    description = ""
    logoBig = "/images/TheChain-logo.png"
    logoSmall = "/images/TheChain-logo.png"
    favicon = "/images/favicon.ico"
    opengraphImage = "/images/TheChain-logo.png"
    twitter = "TheChain16"
    linkedin = "https://www.linkedin.com/company/the-chain-tech/"
    github = "the-chain"
    facebook = ""
    email = "art@wek.io"
    googleTagManager = ""
    highlightJS = true
    copyright = false
    credit = false
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = false

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
